name: Self-hosted runner (scheduled)

# Note that each job's dependencies go into a corresponding docker file.
#
# For example for `run_all_tests_torch_cuda_extensions_gpu` the docker image is
# `huggingface/transformers-pytorch-deepspeed-latest-gpu`, which can be found at
# `docker/transformers-pytorch-deepspeed-latest-gpu/Dockerfile`

on:
  repository_dispatch:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - test_fix_ci_report
env:
  HF_HOME: /mnt/cache
  TRANSFORMERS_IS_CI: yes
  OMP_NUM_THREADS: 8
  MKL_NUM_THREADS: 8
  RUN_SLOW: yes
  SIGOPT_API_TOKEN: ${{ secrets.SIGOPT_API_TOKEN }}
  TF_FORCE_GPU_ALLOW_GROWTH: true
  RUN_PT_TF_CROSS_TESTS: 1

jobs:
  job_1:
    name: Job 1
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout transformers
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install transformers
        run: pip install transformers

      - name: Show installed libraries and their versions
        run: pip freeze

      - name: Job 1 step
        run: |
          python3 utils/get_ci_error_statistics.py --workflow_run_id ${{ github.run_id }} --output_dir job_1 --token ${{ secrets.ACCESS_REPO_INFO_TOKEN }}

      - name: artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: job_links_1
          path: /workspace/transformers/job_1/job_links.json

  job_2:
    name: Job 2
    runs-on: ubuntu-latest
    if: always()
    needs: [
        job_1,
    ]
    steps:
      - name: Checkout transformers
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install transformers
        run: pip install transformers

      - name: Show installed libraries and their versions
        run: pip freeze

      - name: Job 2 step
        run: |
          python3 utils/get_ci_error_statistics.py --workflow_run_id ${{ github.run_id }} --output_dir job_2 --token ${{ secrets.ACCESS_REPO_INFO_TOKEN }}

      - name: artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: job_links_2
          path: /workspace/transformers/job_2/job_links.json
