name: Self-hosted runner (scheduled)

# Note that each job's dependencies go into a corresponding docker file.
#
# For example for `run_all_tests_torch_cuda_extensions_gpu` the docker image is
# `huggingface/transformers-pytorch-deepspeed-latest-gpu`, which can be found at
# `docker/transformers-pytorch-deepspeed-latest-gpu/Dockerfile`

on:
  repository_dispatch:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
      - test_fix_ci_report
env:
  HF_HOME: /mnt/cache
  TRANSFORMERS_IS_CI: yes
  OMP_NUM_THREADS: 8
  MKL_NUM_THREADS: 8
  RUN_SLOW: yes
  SIGOPT_API_TOKEN: ${{ secrets.SIGOPT_API_TOKEN }}
  TF_FORCE_GPU_ALLOW_GROWTH: true
  RUN_PT_TF_CROSS_TESTS: 1

jobs:
  run_extract_warnings:
    name: Extract warnings in CI artifacts
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout transformers
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install transformers
        run: pip install transformers

      - name: Show installed libraries and their versions
        run: pip freeze

      - name: Extract warnings in CI artifacts
        run: |
          python3 utils/get_ci_error_statistics.py --workflow_run_id 4258755021 --output_dir warnings_in_ci --token ${{ secrets.ACCESS_REPO_INFO_TOKEN }}

      - name: artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: job_links
          path: /workspace/transformers/warnings_in_ci/job_links.json
